version: "2"
checks:
  argument-count:
    config:
      threshold: 7
  file-lines:
    enabled: false

plugins:
  pep8:
    enabled: true
    max-line-length: 120

  sonar-python:
    enabled: true

  radon:
    enabled: true

  bandit:
    enabled: true