language: python

python:
  - '3.7'

os:
  - linux

install:
  - pip install -r requirements.txt

  # Extra dependencies for running tests
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov

script:
  - coverage run -m pytest
