language: python

python:
  - 3.5
  - 3.6
  - 3.7

os:
  - linux

install:
  - pip install -r requirements.txt

  # Extra dependencies for running tests
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov
  - pip install coveralls

script:
  - coverage run -m unittest
  - coverage report
  - coveralls
