language: python

python:
  - 3.8

os:
  - linux

before-install:
  # Extra dependencies for running tests
  - pip install coverage
  - pip install coveralls

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest
  - coverage report
  - coveralls
