name: Documentation

on:
  pull_request:
    branches:
      - main

jobs:
  Build-Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-pip-

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install . 
          pip install -r docs/requirements.txt
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Build Documentation
        working-directory: ./docs
        run: make html SPHINXOPTS="-W --keep-going"  # Raise warnings as errors, but keep building anyways.

  Test-Examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get pip cache dir
        id: pip-cache
        run: |
          python -m pip install --upgrade pip
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-py${{ matrix.python-version }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python-version }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python Dependencies
        run: |
          pip install . 
          pip install -r docs/requirements.txt
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Run doctest
        working-directory: ./docs
        run: make doctest
