name: "Test Documentation"

on:
  pull_request:
    branches:
      - master

jobs:
  environment-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
                 
      - name: Install package dependencies
        run: pip install . 
          
      - name: Install documentation dependencies
        run: |
          pip install -r docs/requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended pandoc
    
  build-docs:
    runs-on: ubuntu-latest
    needs: environment-setup
    steps:        
      - name: Run doctest
        working-directory: ./docs
        run: make html SPHINXOPTS="-W --keep-going -n"

        
  test-examples:
    runs-on: ubuntu-latest
    needs: environment-setup
    steps:
      - name: debug
        run: |
          ls
          pwd
          
      - name: Run doctest
        working-directory: ./docs
        run: make doctest
