name: "Test Documentation"

on:
  pull_request:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - uses: ammaraskar/sphinx-action@master
      with:
        pre-build-command: "apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended pandoc"
        docs-folder: docs
        build-command: make html SPHINXOPTS="-W --keep-going -n"
        
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
       
      - name: Install package and dependencies
        run: |
          pip install -r docs/requirements.txt
          sudo apt-get -qq update -y
          sudo apt-get -qq install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended pandoc
          
       
      - name: Run doctest
        working-directory: docs
        run: make doctest
